name: Telegram Test

on:
  workflow_dispatch:        # запускаем вручную
  schedule:
    - cron: "0 7 * * *"     # плюс раз в день в 07:00 UTC (10:00 МСК)

jobs:
  send-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install telegram library
        run: pip install python-telegram-bot

      - name: Run test script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python threads_parser.py

