name: Daily Threads Parser

on:
  schedule:
    - cron: "0 7 * * *"      # каждый день в 07:00 UTC (09:00 Paris)
  workflow_dispatch:         # кнопка «Run workflow» вручную

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install threads-api python-telegram-bot pandas

      - name: Fetch parser script
        run: |
          curl -sL "https://raw.githubusercontent.com/${{ github.repository }}/main/threads_parser.py" \
            -o threads_parser.py

      - name: Run parser
        env:
          THREADS_USERNAME: ${{ secrets.THREADS_USERNAME }}
          THREADS_PASSWORD: ${{ secrets.THREADS_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python threads_parser.py



